# Generated by Django 4.0.5 on 2022-06-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apointment_delete_apoitment_worker_time_of_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apointment',
            name='location',
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=155, unique=True, verbose_name='Location'),
        ),
    ]
