# Generated by Django 4.0.5 on 2022-06-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_apointment_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apointment',
            name='location',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='api.location', verbose_name='location'),
        ),
    ]
