# Generated by Django 4.0.5 on 2022-06-26 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apointment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apointment',
            name='location',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.location', verbose_name='location'),
        ),
    ]
