# Generated by Django 4.0.5 on 2022-06-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_apointment_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time_of_work',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time_of_work',
            field=models.TimeField(default=None, verbose_name='end time pf work'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time_of_work',
            field=models.TimeField(default=None, verbose_name='start time of work'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
