# Generated by Django 4.0.5 on 2022-06-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_schedule_worker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='worker_name',
        ),
    ]
