# Generated by Django 4.0.5 on 2022-06-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_schedule_worker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time_of_work',
            field=models.DateTimeField(default=None, verbose_name='end time pf work'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time_of_work',
            field=models.DateTimeField(default=None, verbose_name='start time of work'),
        ),
    ]
