# Generated by Django 4.0.5 on 2022-06-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_schedule_end_time_of_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='worker_name',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.worker', verbose_name='Worker name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time_of_work',
            field=models.TimeField(default=None, verbose_name='end time pf work'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time_of_work',
            field=models.TimeField(default=None, verbose_name='start time of work'),
        ),
    ]
