# Generated by Django 4.0.5 on 2022-06-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_schedule_worker_name_alter_schedule_end_time_of_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='worker_name',
        ),
    ]
