# Generated by Django 4.0.5 on 2022-06-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_worker_time_of_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='time_of_work',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_of_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.worker', verbose_name='time of work'),
        ),
    ]
