# Generated by Django 4.0.5 on 2022-06-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_schedule_time_of_work_schedule_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='worker',
        ),
        migrations.AddField(
            model_name='worker',
            name='time',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.schedule', verbose_name='Time of work'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time_of_work',
            field=models.TimeField(default=None, unique=True, verbose_name='end time pf work'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time_of_work',
            field=models.TimeField(default=None, unique=True, verbose_name='start time of work'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='place_of_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location', verbose_name='Work location'),
        ),
    ]
