# Generated by Django 4.0.5 on 2022-06-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_schedule_worker_worker_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apointment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.worker', verbose_name='Worker'),
        ),
    ]
