# Generated by Django 4.0.5 on 2022-06-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_apointment_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='apointment',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='apointment',
            name='time_end',
            field=models.TimeField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='apointment',
            name='time_start',
            field=models.TimeField(verbose_name='start'),
        ),
    ]
