# Generated by Django 4.0.5 on 2022-06-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_apointment_date_alter_apointment_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apointment',
            name='time_end',
            field=models.TimeField(unique=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='apointment',
            name='time_start',
            field=models.TimeField(unique=True, verbose_name='start'),
        ),
    ]
