# Generated by Django 4.0.5 on 2022-06-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_apointment_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apointment',
            name='range',
        ),
    ]
