# Generated by Django 4.0.5 on 2022-06-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_timerange_range_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='apointment',
            name='range_time',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.timerange', verbose_name='Time range'),
        ),
    ]
