# Generated by Django 4.0.5 on 2022-06-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_apointment_range_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apointment',
            name='range_time',
        ),
        migrations.DeleteModel(
            name='TimeRange',
        ),
    ]
