# Generated by Django 4.0.5 on 2022-06-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=155, verbose_name='Location'),
        ),
    ]
