# Generated by Django 4.0.5 on 2022-06-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_location_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(blank=True, max_length=155, unique=True, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time_of_work',
            field=models.TimeField(default=None, verbose_name='end time pf work'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time_of_work',
            field=models.TimeField(default=None, verbose_name='start time of work'),
        ),
    ]
