# Generated by Django 4.0.5 on 2022-06-26 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_schedule_day_alter_schedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='time',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.schedule', verbose_name='Time of work'),
        ),
    ]
