# Generated by Django 4.0.5 on 2022-06-26 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_worker_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Thusday', 'Thusday'), ('Wendsday', 'Wendsday'), ('Thersday', 'Thersday'), ('Friday', 'Friday'), ('Seterday', 'Seterday')], max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time_of_work',
            field=models.TimeField(default=None, verbose_name='end time of work'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.workday', verbose_name='Day'),
        ),
    ]
