# Generated by Django 4.0.5 on 2022-06-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_workday_alter_schedule_end_time_of_work_schedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.AddField(
            model_name='worker',
            name='day',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.workday', verbose_name='Day'),
        ),
    ]
