# Generated by Django 4.0.5 on 2022-06-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_schedule_day_worker_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='day',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.workday', verbose_name='Day'),
        ),
    ]
