# Generated by Django 4.0.5 on 2022-06-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_worker_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='day',
        ),
        migrations.DeleteModel(
            name='WorkDay',
        ),
    ]
