# Generated by Django 4.0.5 on 2022-06-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_worker_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='day',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Thusday', 'Thusday'), ('Wendsday', 'Wendsday'), ('Thersday', 'Thersday'), ('Friday', 'Friday'), ('Seterday', 'Seterday')], default=None, max_length=8),
        ),
    ]
