# Generated by Django 4.0.5 on 2022-06-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
    ]
