# Generated by Django 4.0.5 on 2022-06-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Date'),
        ),
    ]
