# Generated by Django 4.0.5 on 2022-06-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_schedule_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Apointment date')),
                ('apointment_start', models.DateTimeField(verbose_name='Apointment time start')),
                ('apointment_end', models.DateTimeField(verbose_name='Apointment time end')),
            ],
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location name'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time_of_work',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='person',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time_of_work',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='place_of_work',
        ),
        migrations.AddField(
            model_name='location',
            name='nameLocation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Location name'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_end',
            field=models.TimeField(null=True, verbose_name='End work'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_start',
            field=models.TimeField(null=True, verbose_name='Start work'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='work_day',
            field=models.CharField(choices=[('MONDAY', 'Понедельник'), ('TUESDAY', 'Вторник'), ('WEDNESDAY', 'Среда'), ('THURSDAY', 'Четверг'), ('FFIDAY', 'Пятница'), ('SATURDAY', 'Суббота'), ('SUNDAY', 'Воскресенье')], default=None, max_length=30, verbose_name='Day'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='worker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='worker_schedule', to='api.worker', verbose_name='schedule to worker'),
        ),
        migrations.AddField(
            model_name='worker',
            name='work_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location', to='api.location', verbose_name='Location of work'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='full_name',
            field=models.CharField(max_length=140, verbose_name='Worker name'),
        ),
        migrations.DeleteModel(
            name='Apointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='apointment_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apointment_worker', to='api.worker', verbose_name='worker to apointment'),
        ),
    ]
