# Generated by Django 4.0.5 on 2022-06-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_appointment_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='apointment_end',
            field=models.TimeField(verbose_name='Apointment time end'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='apointment_start',
            field=models.TimeField(verbose_name='Apointment time start'),
        ),
    ]
