# Generated by Django 4.0.5 on 2022-06-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_appointment_apointment_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='work_day',
            field=models.CharField(choices=[('MONDAY', 'Понедельник'), ('TUESDAY', 'Вторник'), ('WEDNESDAY', 'Среда'), ('THURSDAY', 'Четверг'), ('FRIDAY', 'Пятница'), ('SATURDAY', 'Суббота'), ('SUNDAY', 'Воскресенье')], default=None, max_length=30, verbose_name='Day'),
        ),
    ]
