# Generated by Django 4.0.5 on 2022-07-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_remove_schedule_work_location_schedule_work_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='work_location',
            field=models.ManyToManyField(to='api.location'),
        ),
    ]
