# Generated by Django 4.0.5 on 2022-07-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_schedule_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_published',
        ),
    ]
