# Generated by Django 4.0.5 on 2022-07-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_schedule_is_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='work_location',
            field=models.ManyToManyField(related_name='location', to='api.location', verbose_name='Location of work'),
        ),
    ]
