# Generated by Django 4.0.5 on 2022-07-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_remove_schedule_work_location_schedule_work_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(null=True, verbose_name='Start work')),
                ('time_end', models.TimeField(null=True, verbose_name='End work')),
            ],
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['worker']},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_start',
        ),
        migrations.AddField(
            model_name='schedule',
            name='work_time',
            field=models.ManyToManyField(blank=True, related_name='work_time', to='api.worktime', verbose_name='Work time'),
        ),
    ]
