# Generated by Django 4.0.5 on 2022-07-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_worktime_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['work_time__time_start']},
        ),
    ]
