# Generated by Django 4.0.5 on 2022-07-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_schedule_options_remove_schedule_work_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='work_time',
            field=models.TextField(default=''),
        ),
    ]
