# Generated by Django 4.0.5 on 2022-07-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_schedule_work_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='work_time',
        ),
    ]
