# Generated by Django 4.0.5 on 2022-07-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_appointment_user_remove_schedule_work_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='full_name',
            field=models.CharField(max_length=140, unique=True, verbose_name='Worker name'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('work_location', 'work_day')},
        ),
    ]
