# Generated by Django 4.0.5 on 2022-07-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_alter_worker_full_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
    ]
