# Generated by Django 4.0.5 on 2022-07-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_end',
            field=models.DateTimeField(null=True, verbose_name='End work'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_start',
            field=models.DateTimeField(null=True, verbose_name='Start work'),
        ),
    ]
