# Generated by Django 4.0.5 on 2022-07-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_alter_schedule_time_end_alter_schedule_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_end',
            field=models.TimeField(null=True, verbose_name='End work'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_start',
            field=models.TimeField(null=True, verbose_name='Start work'),
        ),
    ]
